(deftheme spacemacs-dark
  "Created 2017-01-04.")

(custom-theme-set-variables
 'spacemacs-dark
 )

(custom-theme-set-faces
 'spacemacs-dark
 '(cursor ((((class color) (min-colors 89)) (:background "#d0d0d0"))))
 '(custom-button ((((class color) (min-colors 89)) :background "#1c1c1c" :foreground "#b2b2b2" :box (:line-width 2 :style released-button))))
 '(error ((((class color) (min-colors 89)) (:foreground "#e0211d"))))
 '(font-lock-builtin-face ((((class color) (min-colors 89)) (:foreground "#268bd2"))))
 '(font-lock-comment-face ((((class color) (min-colors 89)) (:foreground "#008787" :background "#262626"))))
 '(font-lock-constant-face ((((class color) (min-colors 89)) (:foreground "#d75fd7"))))
 '(font-lock-doc-face ((((class color) (min-colors 89)) (:foreground "#008787"))))
 '(font-lock-function-name-face ((((class color) (min-colors 89)) (:foreground "#d75fd7" :inherit bold))))
 '(font-lock-keyword-face ((((class color) (min-colors 89)) (:inherit bold :foreground "#268bd2"))))
 '(font-lock-negation-char-face ((((class color) (min-colors 89)) (:foreground "#d75fd7"))))
 '(font-lock-preprocessor-face ((((class color) (min-colors 89)) (:foreground "#d75fd7"))))
 '(font-lock-string-face ((((class color) (min-colors 89)) (:foreground "#2aa198"))))
 '(font-lock-type-face ((((class color) (min-colors 89)) (:foreground "#df005f" :inherit bold))))
 '(font-lock-variable-name-face ((((class color) (min-colors 89)) (:foreground "#8787d7"))))
 '(font-lock-warning-face ((((class color) (min-colors 89)) (:foreground "#dc752f" :background "#262626"))))
 '(fringe ((((class color) (min-colors 89)) (:background "#262626" :foreground "#b2b2b2"))))
 '(header-line ((((class color) (min-colors 89)) :background "#080808")))
 '(highlight ((((class color) (min-colors 89)) (:foreground "#b2b2b2" :background "#444444"))))
 '(isearch ((((class color) (min-colors 89)) (:foreground "#262626" :background "#86dc2f"))))
 '(lazy-highlight ((((class color) (min-colors 89)) (:background "#262626" :weight normal))))
 '(link ((((class color) (min-colors 89)) (:foreground "#008787" :underline t))))
 '(link-visited ((((class color) (min-colors 89)) (:foreground "#d75fd7" :underline t))))
 '(match ((((class color) (min-colors 89)) (:background "#444444" :foreground "#86dc2f"))))
 '(minibuffer-prompt ((((class color) (min-colors 89)) (:inherit bold :foreground "#268bd2"))))
 '(region ((((class color) (min-colors 89)) (:background "#444444"))))
 '(secondary-selection ((((class color) (min-colors 89)) (:background "#121212"))))
 '(success ((((class color) (min-colors 89)) (:foreground "#86dc2f"))))
 '(tooltip ((((class color) (min-colors 89)) (:background "#333333" :foreground "#b2b2b2" :bold nil :italic nil :underline nil))))
 '(vertical-border ((((class color) (min-colors 89)) (:foreground "#080808"))))
 '(warning ((((class color) (min-colors 89)) (:foreground "#dc752f"))))
 '(diff-added ((((class color) (min-colors 89)) :background nil :foreground "#67b11d")))
 '(diff-changed ((((class color) (min-colors 89)) :background nil :foreground "#268bd2")))
 '(diff-header ((((class color) (min-colors 89)) :background "#333333" :foreground "#d75fd7")))
 '(diff-indicator-added ((((class color) (min-colors 89)) :background nil :foreground "#67b11d")))
 '(diff-indicator-changed ((((class color) (min-colors 89)) :background nil :foreground "#268bd2")))
 '(diff-indicator-removed ((((class color) (min-colors 89)) :background nil :foreground "#d70000")))
 '(diff-refine-added ((((class color) (min-colors 89)) :background "#67b11d" :foreground "#080808")))
 '(diff-refine-changed ((((class color) (min-colors 89)) :background "#268bd2" :foreground "#080808")))
 '(diff-refine-removed ((((class color) (min-colors 89)) :background "#d70000" :foreground "#080808")))
 '(diff-removed ((((class color) (min-colors 89)) :background nil :foreground "#d70000")))
 '(eldoc-highlight-function-argument ((((class color) (min-colors 89)) (:foreground "#86dc2f" :inherit bold))))
 '(ido-first-match ((((class color) (min-colors 89)) (:foreground "#d75fd7" :inherit bold))))
 '(ido-only-match ((((class color) (min-colors 89)) (:foreground "#86dc2f" :inherit bold))))
 '(ido-subdir ((((class color) (min-colors 89)) (:foreground "#268bd2"))))
 '(info-header-xref ((((class color) (min-colors 89)) (:foreground "#d75fd7" :underline t))))
 '(info-node ((((class color) (min-colors 89)) (:foreground "#d75fd7" :inherit bold))))
 '(info-title-1 ((((class color) (min-colors 89)) (:height 1.4 :inherit bold))))
 '(info-title-2 ((((class color) (min-colors 89)) (:height 1.3 :inherit bold))))
 '(info-title-3 ((((class color) (min-colors 89)) (:height 1.3))))
 '(info-title-4 ((((class color) (min-colors 89)) (:height 1.2))))
 '(mode-line ((((class color) (min-colors 89)) (:foreground "#b2b2b2" :background "#121212" :box (:color "#111111" :line-width 1)))))
 '(mode-line-inactive ((((class color) (min-colors 89)) (:foreground "#b2b2b2" :background "#262626" :box (:color "#111111" :line-width 1)))))
 '(mode-line-buffer-id ((((class color) (min-colors 89)) (:inherit bold :foreground "#d75fd7"))))
 '(show-paren-match ((((class color) (min-colors 89)) (:background "#262626"))))
 '(show-paren-mismatch ((((class color) (min-colors 89)) (:background "#262626"))))
 '(trailing-whitespace ((((class color) (min-colors 89)) :foreground nil :background "#e0211d")))
 '(default ((((class color) (min-colors 89)) (:background "#262626" :foreground "#b2b2b2")))))

(provide-theme 'spacemacs-dark)
